### ISSUE TITLE
Transforms seem to be published at 40 Hz only

### ISSUE THREAD

**Issue by yanjunyangmonash** [ros-industrial/abb_robot_driver#26]
Hi 

My project requires modifying the transformation matrix to get the Jacobine matrix for a virtual link. I tried to get the transformation matrix between two joints using TF.listener, but the frequency is only 40 HZ. I went through all the files but didn't find a publisher that can provide the transformation matrix or jacobian matrix. I would like to know if I miss any information or Is anyone has any idea how to get matrixes in a higher frequency?

Thanks

**Comment by gavanderhoorn** [comment]
@yanjunyangmonash: I've changed the title of the issue to better reflect what your issue is.

Having written that: I believe there are two possible causes here:

 1. the `robot_state_publisher` you're using is not configured to use a publication rate higher than its default (see [wiki/robot_state_publisher: Parameters](http://wiki.ros.org/robot_state_publisher#Parameters), default is 50 Hz)
 2. you don't have EGM. If you don't have EGM, only RWS will be used, which will only support *polling* `JointState`, which limits update frequency to a maximum of around 20 Hz (default: 5 Hz)

With EGM, `JointState` is published at 250 Hz, so if you are using EGM, it's likely that you need to change the `robot_state_publisher` configuration to either also publish at 250 Hz, or set `ignore_timestamp` to `true` (but do read the description of that parameter on the ROS wiki (linked above)).

**Comment by gavanderhoorn** [comment]
Final note(s): the driver does not publish transforms itself. In fact, it does not publish *any* Cartesian information currently.

Transforms are broadcast by the `robot_state_publisher`, which performs Forward Kinematics using the URDF (via the `robot_description` parameter) and incoming `JointState` messages.

The driver *does* publish `JointState` messages (or: the `ros_control` `joint_state_controller` publishes them, but the driver makes the data available for that controller to be able to do that).

**Comment by gavanderhoorn** [comment]
As this is not really an issue with the packages in this repository, and I'm going to assume we've sufficiently addressed your questions.

As such, I'm going to close the issue.

Feel free to keep commenting on it of course, and if it turns out this *is* an issue with the software in this repository, we can re-open.

**Comment by yanjunyangmonash** [comment]
> As this is not really an issue with the packages in this repository, and I'm going to assume we've sufficiently addressed your questions.
> 
> As such, I'm going to close the issue.
> 
> Feel free to keep commenting on it of course, and if it turns out this _is_ an issue with the software in this repository, we can re-open.

Hi, Thanks for your reply. After changing the robot_joint_publihser frequency to 5000, the frequency of /tf can reach about 240HZ (I use rostopic echo). I understand the issue is not relevant to this package, but it would be great to have help as I might need some more support. I would like to know if there is any channel to ask for your help?

**Comment by gavanderhoorn** [comment]
> After changing the robot_joint_publihser frequency to 5000

Why set it to such an unrealistic high number? It cannot publish faster than the rate of the incoming `JointState` messages -- which as I wrote, are published at 250 Hz.

> I would like to know if there is any channel to ask for your help?

for issues with the driver itself, you can post on the tracker (note: *issues*, so bugs).

For general questions about ROS usage, you should post on ROS Answers.

**Comment by yanjunyangmonash** [comment]
> > After changing the robot_joint_publihser frequency to 5000
> 
> Why set it to such an unrealistic high number? It cannot publish faster than the rate of the incoming `JointState` messages -- which as I wrote, are published at 250 Hz.
> 
> > I would like to know if there is any channel to ask for your help?
> 
> for issues with the driver itself, you can post on the tracker (note: _issues_, so bugs).
> 
> For general questions about ROS usage, you should post on ROS Answers.

I remap the /yumi/egm/joint_states to /joint_states and I tried to use 250 Hz for robot_joint_publisher at first and the frequency for /tf was only 200Hz and the only way to have 250Hz for /tf is setting the publishing rate to 5000. Do I do anything wrong?
