### ISSUE TITLE
What's the Yumi/egm/joint_group_velocity_controller's resolution?

### ISSUE THREAD

**Issue by yanjunyangmonash** [ros-industrial/abb_robot_driver#27]
Hi 

I met another problem when I tested my Jacobine matrix. From the Product specification IRB14000, the resolution for each joint is about 0.01 degree, which means the velocity controller's command resolution should be  0.0001745 rad/s from my understanding. But the robot gripper joint doesn't move even I use a much higher value of 0.005 rad/s for the 7th joint. In the test, the joint can move if use any value larger than 0.01. Please let me know if I have anything wrong

**Comment by jontje** [comment]
There are several settings that can affect the EGM motion, for example EGM system configurations (e.g using filtering or not) and RAPID arguments (e.g. position correction gain and specifying correct tool and load).

However, I think this question is more related to the capabilities of the underlying EGM interface, so I suggest that you open a post at the official [ABB Robotics forum](https://forums.robotstudio.com/) regarding this.

**Comment by yanjunyangmonash** [comment]
> ere are several settings that can affect the EGM motion, for example EGM system configurations (e.g using filtering or not) and RAPID arguments (e.g. position correction gain and specifying correct tool and load).
> 
> However, I think this question is more relate

Yes, I did change the EGM system configurations, but it didn't move as well when I changed it back. Is that possible for you to try if this problem also happens to you? I mean use a small value cannot drive the YuMI joints.

**Comment by gavanderhoorn** [comment]
I'm going to close this due to inactivity.

I realise part of that inactivity is on *our* side, but I don't believe there's much to add to what @jontje already wrote.

The `joint_group_velocity_controller` essentially just forwards whatever setpoint it receives directly to the IRC5 controller. Talking about a "resolution" of the `joint_group_velocity_controller` doesn't really work I believe, as that would come down to the resolution of a `double` floating point type (which is the type used by the `joint_group_velocity_controller` for setpoints). A `double` should be capable of representing a number such as `0.0001745`.

If the targetted robot doesn't move with such small velocities, I'd be inclined to agree with @jontje and would recommend to check the configuration on the EGM/IRC5 side.

@yanjunyangmonash: if you did end up asking your question on the ABB Robotics forum: please post a comment here with a link to your question, so we can keep things connected.

**Comment by yanjunyangmonash** [comment]
Hi @jontje, I opened this post at the ABB forum but no one replies yet. If we assume this problem comes from the EGM/IRC5 side, then the parameters that may affect the movement are **use_filtering**; **cond_min_max**; **max_speed_deviation**. And since we use the joint mode, the main functions relate to the robotic arm motion are **EGMActJoint** and **EGMRunJoint**. (Please correct me if I ignored any other parameters or functions that are important)

What I tried are
1. Turn off/on the filter, it didn't work.

2. Modify cond_min_max from 0.5 (your default value) until 0.1. At first I thought the problem might come from here because it is the convergence criteria for all joints. and when I convert 0.5 deg to 0.00872664626 rad, it is the minimum value we can drive the joint using the command `rostopic pub /yumi/egm/joint_group_velocity_controller/command`. Therefore, to achieve a slower speed, I used a smaller cond_min_max value. but the minimum value of the joint speed didn't change.

3. Tested max_speed_deviation from 0.1 to 10. From the manual, it only says this trim the acceleration and deceleration, and I just understand it as the acc. But again, changing this value didn't help

4. Tried few different values of DEFAULT_POSITION_CORR_GAIN from 0 to 1, didn't work.

It would be helpful if you can provide some more information.

Cheers

**Comment by yanjunyangmonash** [comment]
Hi @jontje, I found the problem. In abb_egm_rws_managers/src/egm_manager.cpp, the MIN_SPEED_THRESHOLD is set to 0.5. Once I modified this value, the robot can move at a slower speed.
