### ISSUE TITLE
Using ROS to control the robot

### ISSUE THREAD

**Issue by MHashmi2018** [ros-industrial/abb_robot_driver#28]
Hello,
I had a look at the source code for this driver, and since there is no dependency on the `ros_industrial` driver, I am wondering how it may be possible to use ROS to control an ABB robot via this driver?
For example, in the older version of this driver, we had the driver publish and subscribe to all of the topics that the ros-industrial guidelines mandate (for example, `joint_command`, robot_status`), but I haven't seen any of those publishers and subscribers here.
I would be very grateful for any nudge in the right direction.

**Comment by gavanderhoorn** [comment]
[abb_egm_hardware_interface](https://github.com/ros-industrial/abb_robot_driver/tree/32eb0f48abfd3358cb5a4f3f043f1306a9811b24/abb_egm_hardware_interface) implements a [ros_control](https://github.com/ros-controls/ros_control) compatible [hardware_interface](https://github.com/ros-controls/ros_control/tree/345f5c355bd8720bb25237ef3c093a9b41ce1d47/hardware_interface). This class is responsible for converting data (and control flow) from `ros_control` to the OEM controller and vice versa.

It does not run any controllers itself, nor does it subscribe or publish anything itself (or at least, that's the ideal situation, there are some mitigating circumstances in which it is sort-of allowed to still do some work in the `hardware_interface`).

Running controllers -- such as the [joint_trajectory_controller](http://wiki.ros.org/joint_trajectory_controller) -- is then no longer the responsibility of the driver, but of the `ros_control` [controller_manager](http://wiki.ros.org/controller_manager).

So the reason you can't find any code subscribing to topics or publishing anything or exposing an action server is because that responsibility is delegated to all those other components.

This reduces the responsibilities of a `hardware_interface` such as `abb_egm_hardware_interface` significantly, making it much less work to develop and maintain one.

**Comment by gavanderhoorn** [comment]
I'm going to close this, as I believe we've answered the question.

Please feel free to keep commenting on the issue @MHashmi2018.

**Comment by charmingotm** [comment]
I have some questions about this part too."How can I control ABB by ROS?"and "How can I set up communication between my ABB robot  and ROS?".I really don't know how to use this package after trying to launch "ex1_rws_only.launch"

**Comment by enricovillagrossi** [comment]
Hi,

Have you seen documentation of:
https://github.com/ros-industrial/abb_robot_driver/tree/master/abb_egm_hardware_interface

and
https://github.com/enricovillagrossi/abb_libegm

There is much general information on RobotStudio setup and robot communication configuration; if you need more information, please ask more specific questions. 

Enrico
