### ISSUE TITLE
RWS update rate

### ISSUE THREAD

**Issue by simonschmeisser** [ros-industrial/abb_robot_driver#9]
Great to see this driver released!

We did some experiments with ABBs and the old RAPID driver for motion control and the RWS library for IOs etc. and it worked fairly well. Now handling the state transmission via RWS rather than RAPID sounds like a good idea. But the code has a default rate of 5Hz which is somewhat low. What rates are expected to be possible?

Could subscriptions also be used instead of polling?

**Comment by gavanderhoorn** [comment]
> and the EWS library

you mean RWS, correct?

**Comment by simonschmeisser** [comment]
yes, sorry I meant RWS as we still try to avoid real-time (and thus EGM)

Something like 30-50Hz would be sufficient actually

**Comment by gavanderhoorn** [comment]
> Now handling the state transmission via RWS rather than RAPID sounds like a good idea.

Polling a HTTP endpoint at 50 Hz seems a bit much to me, but perhaps RWS is perfectly fine with that. @jontje?

I'd have expected transferring trajectory points to the controller using RWS would have been a more logical approach, for a first RWS<->`abb_driver` experiment.

> yes, sorry I meant RWS as we still try to avoid real-time (and thus EGM)

you try to avoid what exactly? EGM has a send-only mode, which gets you joint states / Cartesian positions at a far higher resolution that RAPID could give you. You *probably* don't need to setup a real-time kernel to process those on time. It'll just mean you'll sometimes lag a bit.

**Comment by jontje** [comment]
> Could subscriptions also be used instead of polling?

It should be possible to use subscriptions, but they are more complex to handle. For example, there are 3 different priority levels to consider and subscriptions need to be restarted after a restart of the robot controller.

Also, it shouldn't be any issue to use subscriptions in combination with the polling. But this depends on what is desired to be achieved for the application in mind.

> > Now handling the state transmission via RWS rather than RAPID sounds like a good idea.
> 
> Polling an HTTP endpoint at 50 Hz seems a bit much to me, but perhaps RWS is perfectly fine with that. @jontje?

I have a *very vague* memory of reading somewhere that RWS can handle about 10 Hz, but I can't seem to find that text at the moment. I suggest to post a question on the [official Robotics forum](https://forums.robotstudio.com/), otherwise I guess it should be straight-forward to setup some simple tests.

> I'd have expected transferring trajectory points to the controller using RWS would have been a more logical approach, for a first RWS<->`abb_driver` experiment.

When only using RWS, I would recommend doing something like this:

1. Generate the contents for a RAPID module with the trajectory points, and a RAPID procedure to execute the trajectory via RAPID move instructions.
2. Transfer the contents into a RAPID module on the robot controller (e.g. via the `rws/set_file_contents` ROS service).
3. Use the RAPID `Load` instruction to load the new module.
4. Call the RAPID procedure from the loaded module to execute the trajectory.

**Comment by gavanderhoorn** [comment]
@simonschmeisser: I'm going to assume your initial question/comment has been answered/addressed.

There is certainly room for improvement on the non-EGM side. If you do end up implementing (some of) the suggestions by @jontje, let us know how that works out.

In the meantime, I'm closing this.

Feel free to keep commenting on it.
